using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    float xSpeed = 0.0f;
    float ySpeed = 0.0f;
    float zSpeed = 0.0f;
    public bool Rotate = false;
	
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if(Rotate)
	{
		ySpeed = 50;
	}
	else
	{
		ySpeed = 0;
	}
	transform.Rotate(
		xSpeed * Time.deltaTime,
		ySpeed * Time.deltaTime,
		zSpeed * Time.deltaTime
	);
    }
    
    public void ChangeBool()
    {
	Rotate =!Rotate;
    }

}
